### ISSUE TITLE
Добавить кнопку "Посмотреть больше новостей" на страницу newsPage

### ISSUE THREAD

**Issue by GDTuka** [GDTuka/ithub_Student_Practic#40]
Всего изначально будет показываться 4 новости, затем чтобы загрузить больше новостей пользователь должен будет нажать на кнопку которая покажет ещё 4 новости, обратите внимание на то, что нужно будет менять высоту div с классом main в зависимости от того, сколько новостей показывается. В будущем можно будет изменить количество новостей которые будет видеть пользователь, но пока что просто сделать такую возможность

**Comment by EnotOk** [comment]
взял

**Comment by GDTuka** [comment]
сделал
